### PR TITLE
Fix iOS thread clash

### PR DESCRIPTION
**Pull request by yoneapp**
It may crash if you do not run present on the main thread.
Actually, my app crashes.

### CODE REVIEW

**Comment by matt-block** [comment]
Thanks for the PR!

Please switch the base branch from `master` to `development`, I'll handle the release to `master` in a second phase.

**Comment by yoneapp** [comment]
@matt-block 
Hi, I changed the branch.
Is this alright with you?

**Comment by matt-block** [comment]
Thanks, that will do.

Ill review it later today and publish a new release if all is ok.

**Comment by matt-block** [comment]
@yoneapp your fix is included in the new version 1.2.4!

**Comment by yoneapp** [comment]
@matt-block Thanks for review :)

**Pull request merged**
